#!/usr/bin/env python3
# from typing import *


# def solve(n: str) -> str:
def solve(n):
    return n


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    n = input()  # TODO: edit here
    # a = list(map(int, input().split()))  # TODO: edit here
    ans = solve(n)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
