#!/usr/bin/env python3
# from typing import *


# def solve() -> Tuple[str, str, str, str, str, str]:
def solve():
    return 'TIL', 'HAMINGJU', 'MED', 'AFMAELID', 'FORRITUNARKEPPNI', 'FRAMHALDSSKOLANNA!'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():

    g, h, m, n, o, p = solve()
    print(g, h, m, n, o, p)


if __name__ == '__main__':
    main()
