#!/usr/bin/env python3
# from typing import *


# def solve(a: str) -> Tuple[str, str, str, str, str]:
def solve(a):
    return 'Thank', 'you,', a + ',', 'and', 'farewell!'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    g, h, m, n, o = solve(a)
    print(g, h, m, n, o)


if __name__ == '__main__':
    main()
