#!/usr/bin/env python3
# from typing import *


# def solve(a: int) -> Any:
def solve(a):
    return str(a)[::-1]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    a1 = solve(a)
    print(a1)


if __name__ == '__main__':
    main()
