#!/usr/bin/env python3
# from typing import *


# def solve(a: str) -> Any:
def solve(a):
    return 'IGNORE HIM!' if len(set(a)) & 1 else 'CHAT WITH HER!'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    ans = solve(a)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
