#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> int:
def solve(n, a):
    return sum(abs(2 - ix) + abs(2 - iy) for ix, row in enumerate(a) for iy, i in enumerate(row) if i == 1)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = 5
    a = [list(map(int, input().split())) for _ in range(n)]
    a = solve(n, a)
    print(a)


if __name__ == '__main__':
    main()
