#!/usr/bin/env python3
# from typing import *

YES = 'YES'
NO = 'NO'


# def solve(a: int) -> str:
def solve(a):
    return NO if a <= 2 or a & 1 else YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    a1 = solve(a)
    print(a1)


if __name__ == '__main__':
    main()
