#!/usr/bin/env python3
# from typing import *


# def solve(a: str) -> Tuple[str, str, str]:
def solve(a):
    return (a,) * 3


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    e, f, g = solve(a)
    print(e, f, g)


if __name__ == '__main__':
    main()
