#!/usr/bin/env python3
# from typing import *


# def solve(a: int) -> int:
def solve(a):
    return 1000 + (100 * (a - 2020) if a >= 2021 else 0)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    a1 = solve(a)
    print(a1)


if __name__ == '__main__':
    main()
