#!/usr/bin/env python3
# from typing import *


# def solve(a: float) -> int:
def solve(a):
    return round(a + 1e-15)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = float(input())
    a1 = solve(a)
    print(a1)


if __name__ == '__main__':
    main()
