#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int) -> int:
def solve(a, b):
    return a % b


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b = int(input())
    a1 = solve(a, b)
    print(a1)


if __name__ == '__main__':
    main()
