#!/usr/bin/env python3
# from typing import *


# def solve() -> str:
def solve():
    return 'Hello World!'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    # n = int(input())  # TODO: edit here
    # a = list(map(int, input().split()))  # TODO: edit here
    ans = solve()
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
